version: '3'
services:
  # The dev proxy
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile-dev
    depends_on:
    - client
    - api
    ports:
    - '5006:3000'

  # The React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    env_file:
    - ./.env-shared
    volumes:
    - /app/node_modules/
    - gb-sync-client:/app:nocopy
    depends_on:
    - api

  # the API server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    depends_on:
    - db
    - redis
    env_file:
    - ./.env-shared
    volumes:
    - /app/node_modules/
    - gb-sync-api:/app:nocopy

  # database server
  db:
    image: postgres:11.1-alpine
    ports: ["54326:5432"]
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker}
    - POSTGRES_DB=${POSTGRES_DB:-gotbet}

  # local redis server for pubsub and caching
  redis:
    image: redis:5.0.2-alpine
    ports: ["63796:6379"]


volumes:
  gb-sync-client:
    external: true
  gb-sync-api:
    external: true
